configFileVersion: 1.0.0

applicationDetails:
  appName: ComicBookGallary
  # solutionName: ASPNETWebApplication.sln
  solutionPath: Source\ComicBookGallary.sln
  projectPath: Source\ComicBookGallary\ComicBookGallary.csproj
  buildTool: msbuild  #currently supports: msbuild, dotnet, angular
  classification: modern # modern or legacy

notificationSettings:
  notificationType: Teams   #Allowed options: Teams, Email
  webhook: https://outlook.office.com/webhook/8cef57ac-0ab6-485f-a1ac-314b63da536c@5108f34e-9111-4f60-bfc2-e46281215f8a/JenkinsCI/54ae503234954e04bd5a26c7921f4bd7/b98b48f1-d1eb-48b4-a58e-2c35318a9dc9
  recipient: snazir@xfinion.com

testingFramework:
  tool: none   #currently supports: nunit, xunit
  source:
  testResultsLocation:

sonarQubeSettings:
  sonarProjectName: ComicBookGallary
  key: ComicBookGallary

checkmarxSettings:
  checkmarxProjectName: ComicBookGallary  #Name of the app in checkmarx (might be different from the app name above if already taken)
  groupId: 11b25ab0-c498-4e05-a6a6-85ae427a96fa   #group ID is generated by the Checkmarx Jenkins plugin based on the app group

castSettings:
  schemaName:
  applicationName:

pipelineConfig:
  customBuildScript:
